POST http://localhost:8001/issues
Content-Type: application/json

{
  "message": "Dat Ding is einfach kaputt"
}

###
PUT http://localhost:8001/issues/aafd51e8-5dda-438d-bdb7-cc5ba1e06a77/assignee
Content-Type: application/json

{
  "name": "Mark"
}

###
PUT http://localhost:8001/issues/aafd51e8-5dda-438d-bdb7-cc5ba1e06a77/start
Accept: application/json

###
PUT http://localhost:8001/issues/aafd51e8-5dda-438d-bdb7-cc5ba1e06a77/logwork
Content-Type: application/json

{
  "hours": 5.5
}

###
PUT http://localhost:8001/issues/aafd51e8-5dda-438d-bdb7-cc5ba1e06a77/close
Accept: application/json


###
GET http://localhost:8001/issues/aafd51e8-5dda-438d-bdb7-cc5ba1e06a77/events
Accepts: application/json

###
GET http://localhost:8001/issues
Accepts: application/json

###
